# Generated by Django 3.2.7 on 2021-10-05 21:43

import i18nfield.fields
import pretix.base.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pretixbase", "0197_auto_20210914_0814"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventPart",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.CharField(db_index=True, max_length=50)),
                ("name", i18nfield.fields.I18nCharField(max_length=200)),
                ("type", models.CharField(default="start", max_length=5)),
                ("orders", models.ManyToManyField(to="pretixbase.Order")),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
    ]
