# Generated by Django 3.2.7 on 2021-10-05 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0197_auto_20210914_0814'),
        ('pretix_eventparts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpart',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eventparts', to='pretixbase.event'),
            preserve_default=False,
        ),
    ]
