# Generated by Django 3.2.7 on 2021-10-28 22:52

import i18nfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pretix_eventparts", "0003_eventpart_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventpart",
            name="slug",
        ),
        migrations.AddField(
            model_name="eventpart",
            name="category",
            field=i18nfield.fields.I18nCharField(default="", max_length=200),
        ),
    ]
