# Generated by Django 3.2.8 on 2021-10-31 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretix_eventparts", "0005_eventpart_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpart",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
