# Generated by Django 3.2.8 on 2021-10-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_eventparts', '0006_alter_eventpart_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpart',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
