# Generated by Django 3.2.8 on 2021-11-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_eventparts', '0007_alter_eventpart_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpart',
            name='type',
            field=models.CharField(default='start', max_length=6),
        ),
    ]
