# Generated by Django 3.2.8 on 2021-11-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_eventparts', '0008_alter_eventpart_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpart',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
